### ISSUE TITLE
Issues with detecting outstanding migrations

### ISSUE THREAD

**Issue by tjarbo** [pretalx/pretalx-plugin-cookiecutter#6]
Hi,
I wanted to start with the development of plugins for pretalx to further extends its capabilities. First of all thanks a lot for the maintenance of pretalx!

### Description

I encountered is the lack of documentation how migrations are handled and maintained for plugins. Based on all the really cool auto detections of plugins, I was expecting that also migrations work in the same way. Following the starting guide, as no “manage.py” is available, I automatically assume I can use the pretalx commands to do the same. 

I also thought about using “django-admin” but then I do not know to which value to configure `DJANGO_SETTINGS_MODULE` as no settings.py is available. But also running `django-admin makemigrations --settings=pretalx_foobar` had the same effect as described below.

### What do I expect?

If running `python3 -m pretalx makemigrations` or `python3 -m pretalx migrate` it would detect the outstanding changes of the plugin and create/apply the migrations as well.

### What happens instead?

While the “header banner” of pretalx indicates that the plugin has been detected, no migrations are “detected” (if running `python3 -m pretalx makemigrations`) or “pending to be applied” (if running `python3 -m pretalx migrate`)

```
root ➜ /workspaces/GITHUB_pretalx-plugin-development-demo (main) $ python3 -m pretalx makemigrations
You are running pretalx as root, why?
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v2024.2.1                                                              ┃
┃ ┃  ┌─·──╮  ┃  Settings:                                                                      ┃
┃ ┃  │  O │  ┃  Database:  /usr/local/lib/python3.12/site-packages/data/db.sqlite3 (sqlite3)   ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /usr/local/lib/python3.12/site-packages/data/logs                   ┃
┃ ┃  └─┘     ┃  Python:    /usr/local/bin/python3                                              ┃
┃ ┗━━━┯━┯━━━━┛  Source:    /usr/local/lib/python3.12/site-packages/pretalx                     ┃
┃     ╰─╯       Plugins:   pretalx_foobar                                                      ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
No changes detected
````

### How to reproduce?

I created a repository with a devcontainer configuration to easily reproduce the my setup. One major difference to the official guide is, that the plugin development is containerized. That means instead of a virtual environment where I installed pretalx by cloning the repo and run `pip3 install --upgrade-strategy eager -Ue ".[dev]”`, I have installed it from pypi via `pip3 install --upgrade-strategy eager "pretalx[dev]”`. For details about the setup, please checkout the README of the repository.

https://github.com/tjarbo/pretalx-plugin-development-demo

Best regards
tjarbo

**Comment by rixx** [comment]
Ah, yes, that's a bit of a django quirk – for the first migration in an app, you have to name the app specifically to generate the migration. From that point onwards, it'll be picked up by a plain `makemigrations`. I just pushed some [updates to the developer docs](https://github.com/pretalx/pretalx/commit/c641e799939036bfb3a83511e083d64512a385c3) including [this particular oddity](https://docs.pretalx.org/developer/plugins/plugins/#models).

**Comment by tjarbo** [comment]
Thanks a lot for the quick reaction. I noticed in the mean time, that it will work also without the "Please note that to generate your first migration..." and just with `python -m pretalx makemigrations` if the file `mitigations/__init__.py` does exist. Maybe it is worth to add it to the template repository?

**Comment by rixx** [comment]
Done!
